# Generated by Django 5.2 on 2025-06-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_advicecategory_wellnesstip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnesstip',
            name='category',
        ),
        migrations.DeleteModel(
            name='AdviceCategory',
        ),
        migrations.DeleteModel(
            name='WellnessTip',
        ),
    ]
