# Generated by Django 5.2 on 2025-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_remove_wellnesstip_category_delete_advicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('active', 'Very Active'), ('very-active', 'Extremely Active')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='health_goal',
            field=models.CharField(blank=True, choices=[('weight-loss', 'Lose Weight'), ('maintain-weight', 'Maintain Weight'), ('weight-gain', 'Gain Weight'), ('general-health', 'General-health')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
