# Generated by Django 5.2 on 2025-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_passwordhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wants_newsletter',
        ),
        migrations.AddField(
            model_name='customuser',
            name='climate',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('hot', 'Hot/Humid'), ('cold', 'Cold')], max_length=10),
        ),
    ]
