# Generated by Django 5.2 on 2025-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_remove_customuser_wants_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little/no exercise)'), ('light', 'Light (1-3 days/week)'), ('moderate', 'Moderate (3-5 days/week)'), ('active', 'Active (6-7 days/week)'), ('very-active', 'Very Active (2x/day, intense)')], max_length=15),
        ),
    ]
