# Generated by Django 5.2 on 2025-07-02 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_dailyhydration_dailynutrition_dailysleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_anonymization_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_data_anonymized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='retention_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='retention_warnings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DataRetentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warning_sent', 'Retention Warning Sent'), ('final_notice_sent', 'Final Notice Sent'), ('data_anonymized', 'Data Anonymized'), ('account_reactivated', 'Account Reactivated'), ('retention_extended', 'Retention Period Extended')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('days_inactive', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
