# Generated by Django 5.2 on 2025-07-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_customuser_data_anonymization_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutrition',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
    ]
