# Generated by Django 5.2 on 2025-07-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_dailynutrition_sugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kcal', models.PositiveIntegerField()),
                ('protein', models.FloatField(help_text='grams')),
                ('carbs', models.FloatField(help_text='grams')),
                ('fats', models.FloatField(help_text='grams')),
                ('sugar', models.FloatField(default=0.0, help_text='grams')),
                ('time_slept', models.FloatField(help_text='Hours slept')),
                ('water_intake', models.FloatField(help_text='Liters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
