# Generated by Django 5.2 on 2025-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_dailywellness'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailynutrition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='dailysleep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailysleep',
            name='user',
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very-active', 'Very Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='body_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='climate',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('hot', 'Hot/Humid'), ('cold', 'Cold')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='DailyHydration',
        ),
        migrations.DeleteModel(
            name='DailyNutrition',
        ),
        migrations.DeleteModel(
            name='DailySleep',
        ),
    ]
