# Generated by Django 5.2 on 2025-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_volume', models.FloatField(help_text='Calories per given volume')),
                ('volume', models.FloatField(help_text='Volume in ml for which calories apply')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_mass', models.FloatField(help_text='Calories per given mass')),
                ('mass', models.FloatField(help_text='Mass in grams for which calories apply')),
                ('water_percentage', models.FloatField(help_text='Percentage of water content')),
            ],
        ),
    ]
