# Generated by Django 5.2.3 on 2025-06-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_and_drinks', '0002_drink_user_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='calories_per_volume',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories_per_mass',
        ),
        migrations.AddField(
            model_name='drink',
            name='calories_per_ml',
            field=models.FloatField(default=0.0, help_text='Calories per milliliter'),
        ),
        migrations.AddField(
            model_name='drink',
            name='sugar_per_ml',
            field=models.FloatField(default=0.0, help_text='Sugar content per milliliter'),
        ),
        migrations.AddField(
            model_name='food',
            name='calories_per_gram',
            field=models.FloatField(default=0.0, help_text='Calories per gram'),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs_per_gram',
            field=models.FloatField(default=0.0, help_text='Carbohydrate content per gram'),
        ),
        migrations.AddField(
            model_name='food',
            name='fats_per_gram',
            field=models.FloatField(default=0.0, help_text='Fat content per gram'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein_per_gram',
            field=models.FloatField(default=0.0, help_text='Protein content per gram'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.FloatField(default=250.0, help_text='Reference volume in ml for display purposes'),
        ),
        migrations.AlterField(
            model_name='food',
            name='mass',
            field=models.FloatField(default=100.0, help_text='Reference mass in grams for display purposes'),
        ),
        migrations.AlterField(
            model_name='food',
            name='water_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of water content in the food'),
        ),
    ]
