# Generated by Django 5.2 on 2025-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_and_drinks', '0003_remove_drink_calories_per_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='carbs_per_ml',
            field=models.FloatField(default=0.0, help_text='Carbohydrates per milliliter'),
        ),
        migrations.AddField(
            model_name='drink',
            name='fats_per_ml',
            field=models.FloatField(default=0.0, help_text='Fats per milliliter'),
        ),
        migrations.AddField(
            model_name='drink',
            name='protein_per_ml',
            field=models.FloatField(default=0.0, help_text='Protein per milliliter'),
        ),
    ]
