# Generated by Django 5.2 on 2025-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_and_drinks', '0004_drink_carbs_per_ml_drink_fats_per_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sugar_per_gram',
            field=models.FloatField(default=0.0, help_text='Sugar content per gram'),
        ),
    ]
