# Generated by Django 5.2 on 2025-06-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
